language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
matrix:
  allow_failures:
    - python: "3.7-dev"
  fast_finish: true
before_install:
  - pip install pytest-cov
install:
  - pip install -e ".[cloudflare]"
script:
  - python -m pytest tests --cov=.
after_success:
  - pip install codecov
  - codecov
